<a href="https://colab.research.google.com/github/oohlizha/Tugas-Pt-2/blob/main/Tugas_PT_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [2]:
import pandas as pd

In [8]:
data={
    'name':['Bada', 'Soleh', 'Somad', 'Juju', 'Hiro', 'Kenzo', 'Jibe', 'Julian', 'Lizha', 'Mika', 'Xen'],
    'region':['Sokor', 'Jakbar', 'Jaksel', 'Jabar', 'Jaksel', 'Jakut', 'Jateng', 'Susel', 'Jabar', 'Kalsel', 'Jabar'],
    'sales':[90000,34000,87000,23000,45000,340000,540000,85000,34000,87000,84000],
    'expenses':[90000,34000,87000,23000,45000,340000,540000,85000,34000,87000,84000]
       }
df=pd.DataFrame(data)
df

      name  region   sales  expenses
0     Bada   Sokor   90000     90000
1    Soleh  Jakbar   34000     34000
2    Somad  Jaksel   87000     87000
3     Juju   Jabar   23000     23000
4     Hiro  Jaksel   45000     45000
5    Kenzo   Jakut  340000    340000
6     Jibe  Jateng  540000    540000
7   Julian   Susel   85000     85000
8    Lizha   Jabar   34000     34000
9     Mika  Kalsel   87000     87000
10     Xen   Jabar   84000     84000

In [12]:
data={
    'name':['Bada', 'Soleh', 'Somad', 'Juju', 'Hiro', 'Kenzo', 'Jibe', 'Julian', 'Lizha', 'Mika', 'Xen'],
    'region':['Sokor', 'Jakbar', 'Jaksel', 'Jabar', 'Jaksel', 'Jakut', 'Jateng', 'Susel', 'Jabar', 'Kalsel', 'Jabar'],
    'sales':[90000,34000,87000,23000,45000,340000,540000,85000,34000,87000,84000],
    'expenses':[90000,34000,87000,23000,45000,340000,540000,85000,34000,87000,84000]
       }
df=pd.DataFrame(data, index=[0,1,2,3,4,5,6,7,8,9,10])
df

      name  region   sales  expenses
0     Bada   Sokor   90000     90000
1    Soleh  Jakbar   34000     34000
2    Somad  Jaksel   87000     87000
3     Juju   Jabar   23000     23000
4     Hiro  Jaksel   45000     45000
5    Kenzo   Jakut  340000    340000
6     Jibe  Jateng  540000    540000
7   Julian   Susel   85000     85000
8    Lizha   Jabar   34000     34000
9     Mika  Kalsel   87000     87000
10     Xen   Jabar   84000     84000

In [13]:
print(df.loc[8])

name        Lizha
region      Jabar
sales       34000
expenses    34000
Name: 8, dtype: object